package propra22.q8493367.usecases;

/**
 * The Class FileEvent specifies an
 * event generated by the user by creating a new file,
 * by opening or saving a file or by exciting the
 * application.
 */
public class FileEvent {
	
	/** The file event type. */
	private FileEventType fileEventType;
	
	/**
	 * Instantiates a new file event.
	 *
	 * @param fileEventType  the type of the file event
	 */
	public FileEvent(FileEventType fileEventType) {
		this.fileEventType = fileEventType;
	}
	
	/**
	 * Returns the file event type of the file event.
	 *
	 * @return the file event type
	 */
	
	public FileEventType getFileEventType() {
		return fileEventType;
	}
}
